name: Napari_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - dbus=1.13.18
  - expat=2.4.4
  - fontconfig=2.13.1
  - freetype=2.11.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - jpeg=9e
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgomp=12.1.0
  - libnsl=2.0.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libuuid=1.0.3
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=1.1.1q
  - pcre=8.45
  - pip=22.1.2
  - pyqt=5.9.2
  - python=3.9.12
  - python_abi=3.9
  - qt=5.9.7
  - readline=8.1.2
  - setuptools=62.6.0
  - sip=4.19.13
  - sqlite=3.39.0
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.1.0
    - alabaster==0.7.12
    - appdirs==1.4.4
    - asttokens==2.0.5
    - astunparse==1.6.3
    - attrs==21.4.0
    - babel==2.10.3
    - backcall==0.2.0
    - bg-atlasapi==1.0.2
    - bg-space==0.6.0
    - brainglobe-napari-io==0.1.5
    - brainreg==0.3.1
    - brainreg-napari==0.0.5rc0
    - brainreg-segment==0.2.16
    - build==0.8.0
    - cachetools==5.2.0
    - cachey==0.2.1
    - cellfinder-core==0.3.0
    - cellfinder-napari==0.0.19
    - certifi==2022.6.15
    - charset-normalizer==2.1.0
    - click==8.1.3
    - cloudpickle==2.1.0
    - commonmark==0.9.1
    - configobj==5.0.6
    - configparser==5.2.0
    - cycler==0.11.0
    - dask==2022.6.1
    - debugpy==1.6.0
    - decorator==5.1.1
    - docstring-parser==0.14.1
    - docutils==0.18.1
    - entrypoints==0.4
    - executing==0.8.3
    - fancylog==0.2.6
    - flatbuffers==1.12
    - fonttools==4.33.3
    - freetype-py==2.3.0
    - fsspec==2022.5.0
    - future==0.18.2
    - gast==0.4.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.47.0
    - h5py==3.7.0
    - heapdict==1.0.1
    - hsluv==5.0.3
    - idna==3.3
    - imageio==2.19.3
    - imagesize==1.3.0
    - imio==0.2.2
    - imlib==0.1.3
    - importlib-metadata==4.12.0
    - ipykernel==6.15.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.6.1
    - jupyter-client==7.3.4
    - jupyter-core==4.10.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - libclang==14.0.1
    - locket==1.0.0
    - luddite==1.0.2
    - magicgui==0.5.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - meshio==5.3.4
    - micrometa==0.0.11
    - multiprocessing-logging==0.3.3
    - napari==0.4.16
    - napari-console==0.0.4
    - napari-ndtiffs==0.1.2
    - napari-plugin-engine==0.2.0
    - napari-svg==0.1.6
    - natsort==8.1.0
    - nest-asyncio==1.5.5
    - networkx==2.8.4
    - nibabel==4.0.1
    - npe2==0.5.1
    - numexpr==2.8.3
    - numpy==1.23.0
    - numpydoc==1.4.0
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.4.3
    - parso==0.8.3
    - partd==1.2.0
    - pep517==0.12.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - pint==0.19.2
    - pooch==1.6.0
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - psygnal==0.3.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.1
    - pygments==2.12.0
    - pynrrd==0.4.3
    - pyopengl==3.1.6
    - pyparsing==3.0.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyrsistent==0.18.1
    - pyside2==5.15.2.1
    - python-dateutil==2.8.2
    - pytomlpp==1.0.11
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==23.2.0
    - qtconsole==5.3.1
    - qtpy==2.1.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==12.4.4
    - rsa==4.8
    - scikit-image==0.19.3
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - seaborn==0.11.2
    - shiboken2==5.15.2.1
    - six==1.16.0
    - slurmio==0.0.6
    - snowballstemmer==2.2.0
    - sphinx==5.0.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.3.0
    - superqt==0.3.2
    - tables==3.7.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.5.4
    - tomli==2.0.1
    - toolz==0.11.2
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.3.0
    - treelib==1.6.1
    - typer==0.4.1
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - vispy==0.10.0
    - wcwidth==0.2.5
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.0
