name: Cellfinder_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.4.0
  - blosc=1.21.1
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.3.1
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - click=8.1.3
  - cloudpickle=2.1.0
  - cryptography=37.0.4
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.9.0
  - dask-core=2022.9.0
  - dask-image=2021.12.0
  - dav1d=1.0.0
  - dbus=1.13.18
  - distributed=2022.9.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2022.8.2
  - giflib=5.2.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - heapdict=1.0.1
  - icu=58.2
  - idna=3.3
  - imagecodecs=2022.8.8
  - imageio=2.21.2
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libgomp=12.1.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4=4.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - natsort=7.1.1
  - ncurses=6.3
  - networkx=2.8.4
  - numpy=1.23.2
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - partd=1.3.0
  - pcre=8.45
  - pillow=9.2.0
  - pims=0.6.1
  - pip=22.2.2
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.2.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.1.2
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.9.1
  - seaborn=0.11.2
  - setuptools=65.3.0
  - sip=4.19.13
  - six=1.16.0
  - slicerator=1.1.0
  - snappy=1.1.9
  - sortedcontainers=2.4.0
  - sqlite=3.39.2
  - tblib=1.7.0
  - threadpoolctl=2.2.0
  - tifffile=2022.8.12
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=1.0.0
  - zict=2.2.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
